TITLE="Beej's Guide to Learning Computer Science"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.11.2 Copyright © October 9, 2025"

GUIDE_ID=bglcs
BGBSPD_BUILD_DIR?=../../bgbspd

#WEB_IMAGES=$(wildcard img_*.svg img_*.png)

include $(BGBSPD_BUILD_DIR)/source.make
